### PR TITLE
Put tests in functions

### PR DESCRIPTION
**Pull request by tkf**
So that at least `py.test --collect-only ...` should work despite pyjulia setup.  This way, we can (more or less) separate py.test issue from pyjulia issue.

### CODE REVIEW

**Comment by tkf** [comment]
https://github.com/JuliaDiffEq/diffeqpy/pull/10#issuecomment-384133821 should be addressed by https://github.com/JuliaDiffEq/diffeqpy/pull/11/commits/ee410b95b4efd99d9d5bb6e3a5ab80dba91b5f5b

checked with

```sh
.tox/py36/bin/pip uninstall numba
.tox/py36/bin/py.test --pyargs diffeqpy -sv -ra
```

**Comment by tkf** [comment]
Travis fails probably due to numba/numba#2917. Testing if it works with #14

**Comment by ChrisRackauckas** [comment]
This one was covered by the other PR?

**Comment by tkf** [comment]
Yep. Thanks for the merge.

**Pull request closed without merging**
