### PR TITLE
Use the latest version in Julia 1.0.x series

### PR DESCRIPTION
**Pull request by tkf**
This sounds like a safe option.

### CODE REVIEW

**Comment by tkf** [comment]
The test failure in Travis is due to #42 which I think is not related to Julia version.  Python 3 failure in AppVeyor is #37 (will be fixed in next PyJulia).  Python 2 failure in AppVeyor is strange but I'm seeing the test passes in #39 (e.g., https://ci.appveyor.com/project/ChrisRackauckas/diffeqpy/builds/23655746).

**Comment by tkf** [comment]
@ChrisRackauckas It looks like I don't have a write acces. There are no merge button. Can you pull or give me the write access?

**Comment by ChrisRackauckas** [comment]
I just gave you well-deserved admin privs.

**Comment by tkf** [comment]
Cool. Thanks :)

**Pull request merged**
